### ISSUE TITLE
建议加入对ipv6的支持

### ISSUE THREAD

**Issue by bestmikecat** [rurirei/Kitsunebi#11]
原版的Kitsunebi是支持打开ipv6网站的，希望能加入这一功能，另外在关闭代理时程序会闪退，希望改进，并更新至xray1.40，谢谢。

**Comment by rurirei** [comment]
1. `ipv6` will make a test one
2. `bugs of android app` put it off (wait for new one implemented)
3. `xray-core upstream` waiting for more commit

**Comment by rurirei** [comment]
`ipv6` see latest release.

**Comment by bestmikecat** [comment]
ipv6 works fine now, it's a good client software, more features can be added, keep optimizing it, thanks! @rurirei
