### ISSUE TITLE
The App Will Crash after Clicking the Pause Button while the Core is Started

### ISSUE THREAD

**Issue by yahaha-233** [rurirei/Kitsunebi#16]
### what is your environment info (mobile system, app version, etc)?

Android 9.0, Latest version with Xray core 1.4.2

 ### what is your problem meet?
Shown as the title.

 ### if problem reproducible? to describe reproduce steps in details.
Can reoccur every time after the core is started.

 ### paste your configuration here
 ```json
No need to provide configure file.
 ```

**Comment by rurirei** [comment]
try **stop** button of notification channel or **force stop** after crashed.

**Comment by rurirei** [comment]
wait v2.
